### PR TITLE
Issue 55

### PR DESCRIPTION
**Pull request by rnc**

### CODE REVIEW

**Comment by rnc** [comment]
For for issue #55

**Comment by jdcasey** [comment]
This looks pretty good, but I wonder if we're going to need to support partially wildcarded groupIds too, like:

  - `org.jboss.as.*:*@*`

**Comment by rnc** [comment]
*Maybe* ... I've only had a request for wildcard on the artifact so far. If we did need that would it not be a matter of changing the implementation within WildCardMap i.e. its mostly encapsulated at the moment ? The only bit that isn't is https://github.com/release-engineering/pom-manipulation-ext/pull/114/files#diff-4bbf6a93e6938769dff5f0f6d9d0fe32R645

**Comment by jdcasey** [comment]
yep, you're right, it's very well contained. I'm happy with this as a starting point.

**Pull request merged**
