### PR TITLE
squid:S1155 - Collection.isEmpty() should be used to test for emptiness

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule squid:S1155 - Collection.isEmpty() should be used to test for emptiness

You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1155

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by rnc** [comment]
Hi. Thanks for the PR. Can you explain why you have only changed some of the .size calls?

**Comment by m-ezzat** [comment]
Hi @rnc these are the occurrences of the mentioned rule.

**Comment by rnc** [comment]
@m-ezzat Yes, but now the file has some occurrences changed and some not so it looks inconsistent IMHO.

**Comment by m-ezzat** [comment]
@rnc actually, that's because the rule refers only to collections, but I've committed another changes for the rest.

**Comment by rnc** [comment]
@m-ezzat Sorry ,can you rebase please, I didn't realise we were editing the same area of code. Thanks.

**Comment by m-ezzat** [comment]
@rnc NP, it's rebased

**Comment by jdcasey** [comment]
retest this please

**Comment by jdcasey** [comment]
retest this please

**Pull request merged**
