### PR TITLE
PME removes SNAPSHOT from the version but does not use latest increme…

### PR DESCRIPTION
**Pull request by jsenko**
…ntal suffix.

IRC log:
reporter: I have sources in SNAPSHOT version: g:a:1.0-SNAPSHOT,
 when building [...] these sources, PME changes the version to 1.0.0-release-1.
reporter: When I do rebuild [...], PME changes the version again to 1.0.0-release-1.
reporter: Should it be rather changed to 1.0.0-release-2?
reporter: I think there is problem, because PME asks [the REST service] about g:a:1.0-SNAPSHOT and
 [it] doesn't find the best-match version. I think [...] PME should strip -SNAPSHOT before asking [...].

### CODE REVIEW

**Comment by jdcasey** [comment]
add to whitelist

**Comment by rnc** [comment]
@jsenko Thanks! Should we have a test for this?

**Comment by jdcasey** [comment]
@jsenko +1 Thanks! I would love to see a test too, so we don't get regressions on this point later.

**Comment by rnc** [comment]
#351 is an alternative implementation for this.

**Comment by rnc** [comment]
@jsenko Apologies but due to timing we need to make a new PME release for @paulgallagher75 therefore I am closing this in favour #351

**Pull request closed without merging**
