### PR TITLE
Support simplified output and output to file for POM analysis

### PR DESCRIPTION
**Pull request by rnc**

### CODE REVIEW

**Comment by jdcasey** [comment]
retest this please

**Comment by rnc** [comment]
retest this please

**Comment by jdcasey** [comment]
the static port is a problem for CI environments. I'm working on a port-finder to improve this, but we should merge this so I can merge that on top, I guess

**Comment by rnc** [comment]
@jdcasey I just tried experimentally depending on (rather than copying in) the port finder from http-testserver but seem to have issues with the JDK version unfortunately :-(

**Comment by jdcasey** [comment]
closing this, since I merged it by hand as part of: https://github.com/release-engineering/pom-manipulation-ext/pull/264

**Pull request merged**
